linkshorten/main/routes.py
from linkshorten.models import Link
from flask_login import current_user
from linkshorten import db, convert_to_base62, convert_to_base10
from linkshorten.main.utils import my_select, clean_input, my_insert, valid_url, find_url
from flask import render_template, request, abort, Blueprint, redirect, url_for
from base64 import b64encode, b64decode

main = Blueprint('main', __name__)
@main.route("/", methods=['GET', 'POST'])
def home():
	if request.method == 'POST':
		link1 = request.form.get('link1')
		link2 = request.form.get('link2')
		link3 = request.form.get('link3')

		# Random link creation for users who logged in.
		if valid_url(link1) and link2=='':
			longurl = b64encode(link1.encode('ascii')).decode('utf-8')
			user_id = str(current_user).split(' ')[1].strip('>')
			link = Link(link=longurl, isspecial=0, user_id=user_id)
			db.session.add(link)
			db.session.commit()
			return render_template('home.html', link='http://linkshortener.domain/'+convert_to_base62(link.id))
		
		# Special link creation for users who logged in.
		elif current_user.is_authenticated and len(link2) < 15 and valid_url(link1):
			# if not exists; if not  b64decode(find_url(str(convert_to_base10(link1)),'speciallink')).decode('utf-8')
			longurl = b64encode(link1.encode('ascii')).decode('utf-8')
			user_id = str(current_user).split(' ')[1].strip('>')
			my_insert(link2, longurl, user_id, 'speciallink')
			return render_template('home.html', link='http://linkshortener.domain/'+str(link2))

		# Random link creation for any user.
		elif valid_url(link3):
			longurl = b64encode(link3.encode('ascii')).decode('utf-8')
			user_id = str(current_user).split(' ')[1].strip('>')
			link = Link(link=longurl, isspecial=0, user_id=user_id)
			db.session.add(link)
			db.session.commit()
			return render_template('home.html', link='http://linkshortener.domain/'+convert_to_base62(link.id))
		
		else:
			return abort(403)
	
	elif request.method =='GET':
		return render_template('home.html')
	
	else:
		return abort(403)

@main.route("/page/about")
def about():
    return render_template('about.html', title='About')

@main.route("/page/contact")
def contact():
    return render_template('contact.html', title='Contact')

@main.route("/page/links")
def links():
	links = my_select('table_all','link')
	speciallinks = my_select('table_all','speciallink')
	return render_template('links.html', title='Links', links=links, speciallinks=speciallinks)
	

@main.route("/<string:target_link>", methods=['GET'])
def redirecter(target_link):
	if target_link not in ['page']:
		target_link = clean_input(target_link)
		try:
			target_link = find_url(str(convert_to_base10(target_link)),'speciallink')
			return redirect(b64decode(target_link))
		except:
			target_link = find_url(str(convert_to_base10(target_link)),'link')
			return redirect(b64decode(target_link))
		
		else:
			abort(404)	
			

"""

link = Link(link=link1)
db.session.add(link)
db.session.commit()
flash('Your post has been created!', 'success')
if not find_url(str(convert_to_base10()),'speciallink'): #id için kontrol
if not base64_encode(uzunurl) in select uzunurlbase64 from link: # 
insert  isspecial=1 

If URL in list:
* redirect to URL
longurl = b64encode(b'https://www.test4.com').decode('utf-8')
print(longurl)

"""

linkshorten/users/routes.py
from linkshorten import db, bcrypt
from linkshorten.models import User
from flask_login import login_user, current_user, logout_user, login_required
from flask import render_template, url_for, flash, redirect, request, Blueprint
from linkshorten.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm)
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
users = Blueprint('users', __name__)

@users.route("/page/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/page/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/page/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/page/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            return render_template('account.html', title='Account Information Updated!', form=form)
        else:
            logout_user()
            return render_template('home.html', title='Password was incorrect!')

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)

linkshorten/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>

<legend class="border-bottom mb-4">About this project:</legend>

<p style=" padding: 10px; box-shadow: 0px 0px 4px grey">
The main goal of this project is making a web app with generic features.
<br><br>
This application is a simple clone of bitly.
<br><br>
Special links are free; but logging-in is required.
<br><br>
Source code of this project is on github:
<br>
<a href="https://github.com/cemonatk" target="_blank">
	<i class="fa fa-github-square" style="font-size:36px"></i>
</a>
</p>
{% endblock content %}

linkshorten/templates/account.html
{% extends "layout.html" %}
{% block content %}
<h1>Account</h1>
    <h4 class="text-success">
    {% if title != 'Account'  %}
    {{ title }}
    {% endif %}
    </h4>
    <div class="content-section">
       <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <p>Please fill all of the fields.</p>
                
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-success") }}
            </div>
        </form>
    </div>
{% endblock content %}

linkshorten/templates/contact.html
{% extends "layout.html" %}
{% block content %}

    <h1>Contact Page</h1>

<legend class="border-bottom mb-4">Get in touch!</legend>

<p style=" padding: 10px; box-shadow: 0px 0px 4px grey">
Hi I'm Cem,<br><br>  
If you want to get in touch with me, you can use my social accounts.<br><br> Here are my accounts:
<br><br>
<a href="https://www.twitter.com/cemonatk" target="_blank">
	<i class="fa fa-twitter-square" style="font-size:36px"></i> &nbsp;
</a>

<a href="https://www.linkedin.com/in/cemkaragun" target="_blank">
	<i class="fa fa-linkedin-square" style="font-size:36px"></i> &nbsp;
</a>

<a href="https://www.youtube.com/user/cem94" target="_blank">
	<i class="fa fa-youtube-square" style="font-size:36px"></i> &nbsp;
</a>

<a href="https://github.com/cemonatk" target="_blank">
	<i class="fa fa-github-square" style="font-size:36px"></i> &nbsp;
</a>
</p>
{% endblock content %}

linkshorten/templates/home.html
{% extends "layout.html" %}
{% block content %}
    
    {% if title  %}
      <h1 class="text-danger">
      {{ title }}
      </h1>
    {% else %}
      <h1>Welcome to LinkShortener!</h1>
    {% endif %}

{% if not link %} 
<legend class="border-bottom mb-4">Generate it now!</legend>
<div class="form-group">
{% if current_user.is_authenticated %}

<form action="" method="POST">
<label for="basic-url">Random link generation:</label>
<input type="text" class="form-control" name="link1" id="link" type="url" placeholder="URIs must start with http:// or https://">
<br><h4>Or</h4><br>
<label for="basic-url">With special link (Maximum Character limit is 15):</label>
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon3">https://linkshortener.domain/</span>
  </div>
  <input type="text" class="form-control" placeholder="YourSpecialLink" name="link2" id="basic-url" aria-describedby="basic-addon3">
  &nbsp;<button class="btn btn-success" type="submit">Generate!</button>
</div>
</form>

{% else %}

<form action="" method="POST">
<label for="basic-url">Random link generation:</label>
<input type="text" class="form-control" name="link3" id="link" type="url" placeholder="URIs must start with http:// or https://">
<br>
<button class="btn btn-success" type="submit">Generate!</button>
</form>
<br>
<label class="text-danger">You are not logged in, for a special link generation please <p class="font-weight-bold"><a class="text-danger" href="{{ url_for('users.login') }}">Login!</a></p></label>

<div class="input-group-prepend"><br>
  <div style="padding-right: 12px;">
    <span>
      <label>Example special link:</label>
    </span>
    <span class="input-group-text" id="basic-addon3">https://linkshortener.domain/YourSpecialLink</span>
  </div>
  <div>
    <span>
      <label>Example random link:</label>
    </span>
    <span class="input-group-text" id="basic-addon3">https://linkshortener.domain/l4c71d</span></div>
  </div>

{% endif %}
</div>

{% else %}
<script src="https://cdn.rawgit.com/zenorocha/clipboard.js/v2.0.0/dist/clipboard.min.js"></script>
<script type="text/javascript">
  new ClipboardJS('.btn btn-outline-success');
</script>
<legend class="border-bottom mb-4">Generated!</legend>

<h5>Your shortened URL is: </h5><a id="link" href="{{ link }}"><p>{{ link }}</p></a>
<button class="btn btn-outline-success" data-clipboard-action="copy" data-clipboard-target="p" type="submit">Copy to Clipboard</button>
<a href="{{ url_for('main.links') }}"><button class="btn btn-outline-success" type="submit">Check All Links</button></a>
<br><br>
<div id="clipboarded" class="alert alert-success"></div>

<script>
    var pharagraph= document.getElementById("clipboarded");
    pharagraph.style.visibility = "hidden";/*:D*/
    var clipboard = new ClipboardJS('.btn');
    clipboard.on('success', function(e) {
        pharagraph.innerHTML = e.text+" is successfully copied to clipboard!";
        pharagraph.style.visibility = "visible";
    });
    clipboard.on('error', function(e) {
        console.log(e);
    });
    </script>
{% endif %}
{% endblock content %}

linkshorten/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% if title %}
        <title>LinkShortener - {{ title }}</title>
    {% else %}
        <title>LinkShortener</title>
    {% endif %}

    <style type="text/css">
      body { 
        background: url("{{ url_for('static', filename='background-compressed.png') }}") no-repeat center center fixed; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
      }
      .form-control:focus {
        border-color: #28a745!important;
        box-shadow: 0px 0.5px 0.5px rgba(25,200,25,0.1) inset, 0px 0px 8px rgba(25,200,25,0.1);
      }
      h1 {
        margin-top: 50px;
        padding-top: 50px; 
        padding-bottom: 20px; 
      }
      ::-moz-selection {
        color: white;
        background: #28a745!important;
      }
      ::selection {
        color: white;
        background: #28a745!important;
      }
      a:visited, a:link, a:active
      {
        text-decoration: none;
        color: gray;
      }
      a:hover{
        color: #28a745!important;
      }
      table{
        box-shadow: 0px 3px 10px grey;
      }
      tr:nth-child(even){
        background-color: #dddddd;
      }
      tr:nth-child(odd){
        background-color: rgb(195, 195,195);
      }
      td, th{
        padding: 4px;
      }
    </style>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #003c13;">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">LinkShortener!</a>
          <button class="navbar-toggler" type="button" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              <a class="nav-item nav-link" href="{{ url_for('main.contact') }}">Contact</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('main.links') }}">Links</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('main.links') }}">Links</a>
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>


    <main role="main" class="container">
      <div class="row">
        <div class="col-md-6">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}

          {% endblock %}
        </div>
      </div>
    </main>

</body>
</html>

linkshorten/templates/links.html
{% extends "layout.html" %}
{% block content %}
	<h1>Links Page</h1>
	
	{% if current_user.is_authenticated %}

		<legend class="border-bottom mb-4">Latest Special Links:</legend>
		<table style="width: 100%;">
		<tr>
			<th>Target:</th>
		    <th>Shortlink:</th>
	  	</tr>
  		
  		{% for link in speciallinks %}
		<tr>
			<td><a href="{{ link[1] | b64decode }}" target=_blank>{{ link[1] | b64decode }} </a></td>
			<td><a href="{{ link[1] | b64decode }}" target=_blank>linkshortener.domain/{{ link[0] | tobase62 }} </a></td>
		</tr>
		{% endfor %}
		</table>
		
		<br>
		<legend class="border-bottom mb-4">Latest Random Links:</legend>
		<table style="width: 100%;">
		<tr>
			<th>Target:</th>
		    <th>Shortlink:</th>
	  	</tr>

		{% for link in links %}

		<tr>
			<td><a href="{{ link[1] | b64decode }}" target=_blank>{{ link[1] | b64decode}} </a></td>
			<td><a href="{{ link[1] | b64decode }}" target=_blank>linkshortener.domain/{{ link[0] | tobase62  }} </a></td>
		</tr>

		{% endfor %}
		</table><br>

	{% else %}
	
		<label class="text-danger">You are not logged in, to see special links please <p class="font-weight-bold"><a class="text-danger" href="{{ url_for('users.login') }}">Login!</a></p></label>
		<legend class="border-bottom mb-4">Latest Random Links:</legend>
		<table style="width: 100%;">
		<tr>
			<th>Target:</th>
		    <th>Shortlink:</th>
	  	</tr>

		{% for link in links %}
		
		<tr>
			<td><a href="{{ link[1] | b64decode }}" target=_blank>{{ link[1] | b64decode }} </a></td>
			<td><a href="{{ link[1] | b64decode }}" target=_blank>linkshortener.domain/{{ link[0] | tobase62  }} </a></td>
		</tr>

		{% endfor %}
	
		</table><br>
	
	{% endif %}
{% endblock%}

linkshorten/templates/login.html
{% extends "layout.html" %}
{% block content %}
<h1>Login</h1>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Please provide the information requested below to log in the application.</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-success") }}
            </div>
        </form>
{% endblock content %}

linkshorten/templates/register.html
{% extends "layout.html" %}
{% block content %}
<h1>Register</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Please fill all of the fields.</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-success") }}
            </div>
        </form>
    </div>
{% endblock content %}